### PR TITLE
docs(README): add new hephy fox static logos

### PR DESCRIPTION
**Pull request by Cryptophobia**
Signed-off-by: Cryptophobia <aouzounov@gmail.com>

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Do sou have an SVG version of the graphic? That way it way it would look sharp at all screen resolutions.

**Comment by Cryptophobia** [comment]
Thanks for the idea @felixbuenemann . Added SVG to both the website and this repo. 
https://github.com/teamhephy/workflow/pull/122

**Comment by felixbuenemann** [comment]
You can also change the dimensions inside the svg, github only sets a max-width 100% inline style, but I think it looks fine the way it is.

**Comment by Cryptophobia** [comment]
Yes, no need to configure it any more. It is reactive the way it is and the .svg image scales.

**Pull request merged**
