### PR TITLE
New Release v2.21.0

### PR DESCRIPTION
**Pull request by Cryptophobia**
Adding the new release Hephy Workflow v2.21.0

### CODE REVIEW

**Comment by felixbuenemann** [comment]
@Cryptophobia Great news! – Are you looking for specific feedback/testing?

I'm going to push the new release to our staging clusters in the next couple of days.

**Comment by Cryptophobia** [comment]
@felixbuenemann, that would be great if you could upgrade and give some feedback! It has already been running on my clusters but I need more feedback from users who use Hephy Workflow under more load. I'm only running a few simple webapps/services on my clusters.

**Comment by felixbuenemann** [comment]
I haven't had any problem reports, so I've rolled out v2.21.0 to production today.

**Comment by Cryptophobia** [comment]
@felixbuenemann Great to hear! We can begin planning some features for the next release then.

**Pull request merged**
