### PR TITLE
feat(storage): support for configuring the S3 endpoint

### PR DESCRIPTION
**Pull request by rwos**
part of https://github.com/teamhephy/workflow/issues/52

Guess I start here - whether you want to keep this open until everything else is done, or merge right away, your call 😄

### CODE REVIEW

**Comment by kingdonb** [comment]
This is a good start – so, we support some other storage endpoints already, and they don't use the "s3" configuration section

Does this change work by itself? (with the other updates that you placed in https://github.com/teamhephy/distribution/pull/1 , of course I mean)

I'm trying to decide if we should actually add a section for non-s3 storage systems that are not supported by name, and if we need to go down the road of adding each new storage system we want to support so that users are not manually setting endpoint knobs on systems that are (or should be) defined in an upstream s3 library supporting repo somewhere...

**Comment by kingdonb** [comment]
I am pretty sure they are all basically using S3 API, I just don't know how the components all support this quite inside-and-out.

The teamhephy/s3-uploader repo, for one I think, would have to be used and supporting all three... as AIUI this is the component that handles WAL backups from the postgres component, and the capability of running on-cluster postgres is a requirement of every supported platform.

I haven't looked deeply enough at this to say for sure, but I have every intention of digging deeper inside of the next 7 days or thereabouts!  We are excited to add support for DigitalOcean Spaces at least in the near future.

We want to do this for Spaces so that we can add them to the list of supported platforms quickly after their managed Kubernetes goes into general availability.  (And IBM Cloud has had most of these and all of this kind of supporting infrastructure available in GA already for at least 6 months.)

**Comment by rwos** [comment]
Well if it's all s3 anyway, we can simplify a lot there 👍 

> [ DigitalOcean Spaces ]

from [a quick glance at the docs](https://www.digitalocean.com/docs/spaces/resources/s3cmd/), that should indeed just work by setting that new `endpoint` param to `https://nyc3.digitaloceanspaces.com` (once all the components know about the parameter, ofc)

**Comment by kingdonb** [comment]
Definitely seems like there are some opportunities to simplify the config, but I think for first-class support like we have with the other storage APIs, it would be better to save the user from needing to know about `endpoint`...

In other words, if it's true that there's only one region and only one possible setting for endpoint in the configuration of a DigitalOcean Spaces-backed workflow then a user who selects `digitalocean` as the storage backend by setting `global.storage`, not have any more work to do other than setting access keys and secrets.

It should be just the same as someone who is configuring `azure` or `gcs` backends, which I think have the same characteristic of a single region, ... well that doesn't sound right, but I don't see a setting for region in either GCS or Azure storage sections.  (Actually I think for AZ the region is an innate characteristic of the AccountName/AccountKey pair.  Maybe the same for key_json in GCS.)

Regardless, if there are no regions in Spaces, then we can make the config just as easy.

Anyway if your patch enables some users who know what they're doing to use these other storage backends by setting endpoint, without any "first-class support," then I don't see any reason why it shouldn't be merged first, ahead of all that.

**Comment by rwos** [comment]
Ah, that makes sense - yeah, that should be easy then, just some helm chart stuff to make that work.

**Comment by Cryptophobia** [comment]
I think for now it would be good to merge this in and allow users to set the endpoint of S3 to whatever they need it to be. After all the API of S3 is called `S3` and the idea of S3 does not have to be connected to AWS in any way even though it is right now. That's what `S3-compatible` means anyways.

Eventually I agree with @kingdonb  that separating the configurations out would be a good idea.


> part of #52
> 
> Guess I start here - whether you want to keep this open until everything else is done, or merge right away, your call smile

Can you submit all the PRs and then give me links in Slack to what needs to be merged all at once? I would want to do some commenting and testing before we merge everything.

**Comment by kingdonb** [comment]
Yeah we can merge this in for v2.20 as far as I'm concerned

**Comment by Cryptophobia** [comment]
> Yeah we can merge this in for v2.20 as far as I'm concerned

I'm ready to start making v2.20 release and I'm not sure @rwos is ready with all the PRs. Are all the PRs for this feature ready @rwos ?

**Comment by rwos** [comment]
@Cryptophobia yes, they're all linked to https://github.com/teamhephy/workflow/issues/52
Additionally, slugbuilder, slugrunner, and dockerbuilder will need the new object-storage-cli once that is merged and built.

**Pull request closed without merging**
