### PR TITLE
WIP: Feat s3 endpoint

### PR DESCRIPTION
**Pull request by kingdonb**
Supporting changes for teamhephy/postgres#6

Perhaps the default setting should remain as "true"?

These commits may still need to be cleaned up so they conform to the style guide...

### CODE REVIEW

**Comment by yebyen** [comment]
So, I also hit a catch-22 while I was testing this...

There was something that required me to set an endpoint, so I set "sfo2" since I noticed a piece of the database backup code which would use region to inform "create_bucket" -- I have no idea if this will work against the DigitalOcean API, I had already created the buckets, but this seemed to fit.

Then I tried builder, and noticed:
```
2018/11/24 19:14:21 Invalid region provided: sfo2
remote: 2018/11/24 19:14:26 Error running git receive hook [build pod exited with code 1, stopping build]
To ssh://hephy.rocks:30075/rocksolidapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@hephy.rocks:30075/rocksolidapp.git'
```

Maybe it would work if I was able to set an empty region, but like I said, something else had prohibited me from leaving the region value blank.  Will follow up later...

**Comment by yebyen** [comment]
I also noticed, with regard to DO and kops, that having configured ingress, I still had a LoadBalancer provisioned by deis-builder, which was expected; but it never picked up the backing service and routed traffic to it.  I don't know if this would have worked with the managed Kubernetes service, I assume so.  Kops support for DigitalOcean is alpha, but "Limited release" managed k8s probably has this solved already.

**Comment by duanhongyi** [comment]
I have shut down my rp(#74), use this RP uniformly

**Comment by kingdonb** [comment]
This was not closed on purpose... whoops

**Pull request closed without merging**
